### ISSUE TITLE
shuffled_data = data[shuffle_indices]  IndexError: too many indices for array

### ISSUE THREAD

**Issue by mrinal18** [danielegrattarola/twitter-sentiment-cnn#8] opened 2017-06-27 05:32 UTC
======================= START! ========================
	data_helpers: loading positive examples...
	data_helpers: [OK]
	data_helpers: loading negative examples...
	data_helpers: [OK]
	data_helpers: cleaning strings...
	data_helpers: [OK]
	data_helpers: generating labels...
	data_helpers: [OK]
	data_helpers: concatenating labels...
	data_helpers: [OK]
	data_helpers: padding strings...
	data_helpers: [OK]
	data_helpers: building vocabulary...
	data_helpers: [OK]
	data_helpers: building processed datasets...
	data_helpers: [OK]

Flags:
	batch_size = 100
	checkpoint_freq = 1
	custom_input = 
	device = cpu
	embedding_size = 128
	epochs = 3
	evaluate_batch = False
	filter_sizes = 3,4,5
	load = None
	num_filters = 128
	reduced_dataset = 1
	save = True
	save_protobuf = False
	test_data_ratio = 10
	train = True
	valid_freq = 1

Dataset:
	Train set size = 1420766
	Test set size = 157862
	Vocabulary size = 274562
	Input layer size = 117
	Number of classes = 2

Output folder: /home/bizviz/Desktop/twitter-sentiment-cnn/output/run20170626-185836
2017-06-26 20:00:41.322072: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 20:00:42.065691: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 20:00:42.559938: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 20:00:43.504129: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 20:00:43.704418: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Data processing OK, creating network...
Traceback (most recent call last):
  File "twitter-sentiment-cnn.py", line 299, in <module>
    test_batches = list(batch_iter(zip(x_test, y_test), FLAGS.batch_size, 1))
  File "/home/bizviz/Desktop/twitter-sentiment-cnn/data_helpers.py", line 183, in batch_iter
    **shuffled_data = data[shuffle_indices]
IndexError: too many indices for array**

I am getting this error and not quite sure how to solve it. can you please help me with it?

**Comment by mrinal18** [comment] 2017-06-27 07:57
[27 25 13 19  4 28 21  7 15  8 10  0 29 16  9 17  3 14 22 18  5  1  6 24 20
 12 11 26 23  2]
This is the output of shuffle_indices that i'm getting. 

Kindly see what the problem is please

**Comment by danielegrattarola** [comment] 2017-06-27 16:07
Hi,  
Can you give me the exact combination of flags needed to reproduce this, please?

**Comment by mrinal18** [comment] 2017-06-27 16:11
i am training it using your tutorial

"python twitter-sentiment-cnn.py --train --save"

**Comment by danielegrattarola** [comment] 2017-06-27 16:17
Works on my machine, sorry.   
If I remember correctly in a previous issue you said you were using Python 3: could you run the same command after cloning the repo (and setting everything up) in Python 2.7? 

Cheers, 
Daniele

**Comment by mrinal18** [comment] 2017-06-28 10:04
i found the issue. although, how much time is it taking in your system to find out the sentiment of a sentence?

**Comment by danielegrattarola** [comment] 2017-06-28 10:10
If you mean GPU computation time for the forward propagation of a single sentence, then it's in the milliseconds order. 
If you mean total runtime for a single prediction without training, then it's some minute because this repo was not really conceived for OOB usage, but rather to teach people how neural networks work with the whole training-testing procedure. 
Since you found a solution I'll close the issue.

**Closed as completed by danielegrattarola** 2017-06-28 10:10 UTC
