### ISSUE TITLE
Error while running python vocab_builder.py

### ISSUE THREAD

**Issue by deepkshikha** [danielegrattarola/twitter-sentiment-cnn#14] opened 2018-02-06 09:33 UTC
vocab_builder: loading...
	data_helpers: loading positive examples...
	data_helpers: [OK]
	data_helpers: loading negative examples...
	data_helpers: [OK]
	data_helpers: cleaning strings...
	data_helpers: [OK]
	data_helpers: generating labels...
	data_helpers: [OK]
	data_helpers: concatenating labels...
	data_helpers: [OK]
vocab_builder: padding...
Killed

**Comment by danielegrattarola** [comment] 2018-02-06 09:43
Closing this as duplicate of issue https://github.com/danielegrattarola/twitter-sentiment-cnn/issues/13.

**Closed as completed by danielegrattarola** 2018-02-06 09:43 UTC

**Comment by deepkshikha** [comment] 2018-02-06 10:19
Ok
